login: /iam/api/v1/users/login

apworkshop:
  model_types: /iqi/api/v1/apworkshop/modelTypes

scenes:
  scenes: /iqi/api/v1/scenes
  scene_labels: /iqi/api/v1/scene-labels


file_server:
  upload: /file_server/api/v1/files

